try {
  console.log('try')
} catch (e) {
  console.log('error')
} finally {
  console.log('finally')  
}
